date_format:            "%b %-d, %Y"
disable_disk_cache:     true

permalink:              /:categories/:title/
permalink:              "/:title/"
paginate_path:          "/page:num"

sass:
  sass_dir:             _scss
  style:                :compressed
  sourcemap:            never

collections:
  defaults:
    output:             true
    permalink:          /:path/
  pages:
    output:             true
    permalink:          /:path/

defaults:
  - scope:
      path:             "_defaults"
    values:
      type:             "defaults"
  - scope:
      path:             "_pages"
    values:
      type:             "pages"
  - scope:
      path:             "_posts/blog"
    values:
      type:             "blog"
  - scope:
      path:             "_posts/collections"
    values:
      type:             "collections"

collections:
  category:
    output:             true
  defaults:
    output:             true
    permalink:          /:path/    
  pages:
    output:             true
    permalink:          /:path/

exclude:
  - .git
  - .jekyll-cache
  - .Gemfile
  - .Gemfile.lock