disable_disk_cache: true

date_format: "%b %-d, %Y"

permalink: "/:title/"
paginate_path: "/page:num"

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "_pages"
    values:
      type: "pages"
  - scope:
      path: "_posts/blog"
    values:
      type: "blog"
  - scope:
      path: "_posts/collections"
    values:
      type: "collections"

sass:
  sass_dir: assets/css/_scss
  style: :compressed
  sourcemap: never

plugins:
  - jekyll-postcss-v2
  - jekyll-archives
  - jekyll-contentblocks

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: templates/categories
  permalinks:
    category: "/categories/:name/"  

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - .gitignore