disable_disk_cache: true

date_format: "%b %-d, %Y"

permalink: "/:title/"
paginate_path: "/page:num"

sass:
  sass_dir: assets/css/_scss
  style: :compressed
  sourcemap: never

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "_pages"
    values:
      type: "pages"
  - scope:
      path: "_posts/blog"
    values:
      type: "blog"
  - scope:
      path: "_posts/collections"
    values:
      type: "collections"

exclude:
  - .git
  - .jekyll-cache
  - .Gemfile
  - .Gemfile.lock