name: workflow_actions

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: ruby_setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: node_setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install_dependencies
        run: |
          npm install
          npm install --only=dev

      - name: build
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          format_output: true
          prettier_opts: '{ "useTabs": false }'

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages